server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sidecar
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
 
  application:
    name: codingtest
    
  management:
    endpoints:
     web:
      exposure:
        include: "*"
    port: 9000
  
# Below are redis cache settings  
  
#  cache:#    type: redis
#    redis:#     cache-null-values: false
#      time-to-live: 600000
#      use-key-prefix: FALSE
#  redis:#    host: localhost
#    port: 6379
    
 