server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sidecar
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
 
  application:
    name: codingtest
    
  management:
    endpoints:
     web:
      exposure:
        include: "*"
    port: 9000
  
 
    
 